Repository microsoft/ALAppExtensions, pull requests merged in 2022-12, with the labels that each got.

#21244 Copy filters on test suite update
  Modules/DevTools/TestFramework/TestRunner/src/TestSuiteMgt.Codeunit.al
Labels: processing-PR

#21234 Add new permission Types for SAS
  Modules/System Tests/Azure Storage Services Authorization/src/StorServAccountSASTest.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/SAS/SASPermission.Enum.al
Labels: processing-PR

#21203 Fix SharePoint AcquireToken
  Modules/System/SharePoint Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al
Labels: processing-PR

#21210 Enable support to specify the optional Signed Encryption Scope (ses) for API Version 2020-12-06
  Modules/System/Azure Storage Services Authorization/src/SAS/SASParameters.Table.al
  Modules/System/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/StorServAuthImpl.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/StorageServiceAPIVersion.Enum.al
Labels: processing-PR

#21236 Add IQBanking to Connectivity Apps
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, connectivity-apps

#21363 Added Wise Banking to Connectivity Apps
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, connectivity-apps

#21330 Add build modes
  .github/AL-Go-Settings.json
  .github/DeliverToBCFeed.ps1
  Modules/.AL-Go/CompileAppInBcContainer.ps1
  Modules/.AL-Go/settings.json
Labels: infrastructure
