Repository microsoft/ALAppExtensions, pull requests merged in 2023-06, with the labels that each got.

#23629 Add ready SAS authorization
  Modules/System/Azure Storage Services Authorization/src/ReadySAS/StorServAuthReadySAS.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/StorServAuthImpl.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/StorageServiceAuthorization.Codeunit.al
Labels: processing-PR

#23608 Add new storage service API versions
  Modules/System/Azure Storage Services Authorization/src/StorageServiceAPIVersion.Enum.al
Labels: processing-PR

#22149 Two new scenarios for GL entries and
  Other/Tests/BCPT-SampleTests/src/BCPTPostGLEntries.Codeunit.al
  Other/Tests/BCPT-SampleTests/src/BCPTPostPurchInv.Codeunit.al
  Other/Tests/BCPT-SampleTests/src/TestCodeunitsWithParams.Enum.al
Labels: ships-in-future-update, processing-PR

#23793 Update package versions
  Build/Packages.json
Labels: automation

#23806 Lock Labels for Storage Service Authorization
  Apps/W1/AuditFileExport/app/src/ExportEngine/AuditFileExportMgt.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/SharedKey/StorServAuthSharedKey.Codeunit.al
Labels: processing-PR

#23863 Update package versions
  Build/Packages.json
Labels: automation

#23932 Update package versions
  Build/Packages.json
Labels: automation
