Repository microsoft/ALAppExtensions, pull requests merged in 2023-10, with the labels that each got.

#24858 Removing dependency on SAS token
  .github/AL-Go-Settings.json
  .github/RELEASENOTES.copy.md
  .github/workflows/CICD.yaml
  .github/workflows/IncrementVersionNumber.yaml
  .github/workflows/PullRequestHandler.yaml
  .github/workflows/UpdateGitHubGoSystemFiles.yaml
  .github/workflows/_BuildALGoProject.yaml
  Modules/System Test Libraries/Translation/src/TranslationTestTable.Table.al
  Modules/System Tests/Azure AD Plan/src/AzureADPlanTests.Codeunit.al
  Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al
  Modules/System Tests/Data Compression/src/DataCompressionTests.Codeunit.al
  Modules/System Tests/Email/src/EmailAccountsTest.Codeunit.al
  Modules/System Tests/Retention Policy/src/RetentionPeriodTest.Codeunit.al
  Modules/System Tests/Translation/app.json
  Modules/System Tests/Translation/src/TranslationTests.Codeunit.al
  Modules/System Tests/URI/src/UriTest.Codeunit.al
  Modules/System/Azure AD Plan/src/PlanIds.Codeunit.al
  Modules/System/Azure AD Plan/src/PlanInstaller.Codeunit.al
  Modules/System/Azure AD Plan/src/PlanUpgrade.Codeunit.al
  Modules/System/Azure AD Plan/src/PlanUpgradeTag.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSOperationResponse.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSWebRequestHelper.Codeunit.al
  Modules/System/Data Compression/src/DataCompression.Codeunit.al
  Modules/System/Data Compression/src/DataCompressionImpl.Codeunit.al
  Modules/System/Edit in Excel/src/EditInExcel.Codeunit.al
  Modules/System/Edit in Excel/src/EditInExcelWorkbookImpl.Codeunit.al
  Modules/System/Edit in Excel/src/EditinExcelImpl.Codeunit.al
  Modules/System/Email/src/Account/EmailAccount.Codeunit.al
  Modules/System/Email/src/Account/EmailAccountImpl.Codeunit.al
  Modules/System/Email/src/Email/Outbox/EmailEditor.Page.al
  Modules/System/Entitlements/Dynamics365BusinessCentralEssentialAttach.Entitlement.al
  Modules/System/Entity Text/src/AzureOpenAiImpl.Codeunit.al
  Modules/System/Guided Experience/src/Guided Experience/GuidedExperienceImpl.Codeunit.al
  Modules/System/Guided Experience/src/Guided Experience/GuidedExperienceUpgrade.Codeunit.al
  Modules/System/Retention Policy/src/Apply Retention Policy/ApplyRetentionPolicyImpl.Codeunit.al
  Modules/System/Retention Policy/src/Retention Period/RetentionPeriodEnum.Enum.al
  Modules/System/Retention Policy/src/Retention Period/RetentionPeriodImpl.Codeunit.al
  Modules/System/Telemetry/src/Logging/Telemetry.Codeunit.al
  Modules/System/Translation/src/Translation.Codeunit.al
  Modules/System/Translation/src/Translation.Page.al
  Modules/System/Translation/src/TranslationImplementation.Codeunit.al
  Modules/System/URI/src/Uri.Codeunit.al
  Modules/System/URI/src/UriKind.Enum.al
  System Application Modules/.AL-Go/cloudDevEnv.ps1
  System Application Modules/.AL-Go/localDevEnv.ps1
  System Application/.AL-Go/cloudDevEnv.ps1
  System Application/.AL-Go/localDevEnv.ps1
  Test Framework/.AL-Go/cloudDevEnv.ps1
  Test Framework/.AL-Go/localDevEnv.ps1
  Test Stability Tools/.AL-Go/cloudDevEnv.ps1
  Test Stability Tools/.AL-Go/localDevEnv.ps1
Labels: internal

#24966 Update package versions
  Build/Packages.json
Labels: automation

#24803 AL Rest Client
  .github/AL-Go-Settings.json
  Modules/System Tests/Rest Client/app.json
  Modules/System Tests/Rest Client/src/HttpAuthenticationTests.Codeunit.al
  Modules/System Tests/Rest Client/src/HttpContentTests.Codeunit.al
  Modules/System Tests/Rest Client/src/RequestMessageTests.Codeunit.al
  Modules/System Tests/Rest Client/src/RestClientTests.Codeunit.al
  Modules/System Tests/Rest Client/src/TestHttpClientHandler.Codeunit.al
  Modules/System/Rest Client/app.json
  Modules/System/Rest Client/src/Authentication/HttpAuthentication.Interface.al
  Modules/System/Rest Client/src/Authentication/HttpAuthenticationAnonymous.Codeunit.al
  Modules/System/Rest Client/src/Authentication/HttpAuthenticationBasic.Codeunit.al
  Modules/System/Rest Client/src/HttpClientHandler/HttpClientHandler.Codeunit.al
  Modules/System/Rest Client/src/HttpClientHandler/HttpClientHandler.Interface.al
  Modules/System/Rest Client/src/HttpContent.Codeunit.al
  Modules/System/Rest Client/src/HttpContentImpl.Codeunit.al
  Modules/System/Rest Client/src/HttpMethod.Enum.al
  Modules/System/Rest Client/src/HttpRequestMessage.Codeunit.al
  Modules/System/Rest Client/src/HttpRequestMessageImpl.Codeunit.al
  Modules/System/Rest Client/src/HttpResponseMessage.Codeunit.al
  Modules/System/Rest Client/src/HttpResponseMessageImpl.Codeunit.al
  Modules/System/Rest Client/src/RestClient.Codeunit.al
  Modules/System/Rest Client/src/RestClientImpl.Codeunit.al
Labels: processing-PR

#24903 Parse blob names with hierarchical namespace
  Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al
  Modules/System Tests/Azure Blob Services API/src/ABSTestLibrary.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSContainerContentHelper.Codeunit.al
Labels: processing-PR

#25021 Update package versions
  Build/Packages.json
Labels: automation

#25084 SetLoadFields, SetAutoCalcFields, IsEmtpy
  Apps/W1/EssentialBusinessHeadlines/app/src/codeunits/EssBusHeadlineSubscribers.Codeunit.al
  Apps/W1/EssentialBusinessHeadlines/app/src/codeunits/EssentialBusHeadlineMgt.Codeunit.al
  Apps/W1/EssentialBusinessHeadlines/app/src/queries/BestSoldItemHeadline.Query.al
  Apps/W1/EssentialBusinessHeadlines/app/src/queries/SalesIncreaseHeadline.Query.al
  Apps/W1/EssentialBusinessHeadlines/app/src/queries/TopCustomerHeadline.Query.al
Labels: processing-PR

#25055 Add OnBeforeSearchTable publisher for "Search in company data" feature
  Apps/W1/DataSearch/App/DataSearchEvents.codeunit.al
  Apps/W1/DataSearch/App/DataSearchInTable.codeunit.al
Labels: processing-PR
