Repository microsoft/ALAppExtensions, pull requests merged in 2023-03, with the labels that each got.

#21063 Separate Modules to multiple AL-Go projects
  .github/AL-Go-Settings.json
  .github/workflows/CICD.yaml
  .github/workflows/PullRequestHandler.yaml
  Build/Scripts/CompileAppInBcContainer.ps1
  Build/Scripts/NewBcContainer.ps1
  CODEOWNERS
  Modules/.AL-Go/settings.json
  System Application Modules/.AL-Go/cloudDevEnv.ps1
  System Application Modules/.AL-Go/localDevEnv.ps1
  System Application Modules/.AL-Go/settings.json
  System Application/.AL-Go/CompileAppInBcContainer.ps1
  System Application/.AL-Go/ImportTestToolkitToBcContainer.ps1
  System Application/.AL-Go/NewBcContainer.ps1
  System Application/.AL-Go/cloudDevEnv.ps1
  System Application/.AL-Go/localDevEnv.ps1
  System Application/.AL-Go/settings.json
  Test Framework/.AL-Go/CompileAppInBcContainer.ps1
  Test Framework/.AL-Go/ImportTestToolkitToBcContainer.ps1
  Test Framework/.AL-Go/NewBcContainer.ps1
  Test Framework/.AL-Go/cloudDevEnv.ps1
  Test Framework/.AL-Go/localDevEnv.ps1
  Test Framework/.AL-Go/settings.json
Labels: infrastructure

#22515 Add Breaking Change Check
  .github/AL-Go-Settings.json
  .gitignore
  Build/BuildConfig.json
  Build/Rulesets/module.ruleset.json
  Build/Scripts/CompileAppInBcContainer.ps1
  Build/Scripts/EnlistmentHelperFunctions.psm1
  Build/Scripts/GuardingV2ExtensionsHelper.psm1
  Modules/System/Azure AD Plan/src/PlanIds.Codeunit.al
  Modules/System/Guided Experience/src/Assisted Setup/AssistedSetup.Table.al
  Modules/System/Guided Experience/src/Assisted Setup/AssistedSetupLog.Table.al
  Modules/System/Guided Experience/src/Manual Setup/BusinessSetupIcon.Table.al
  Modules/System/Guided Experience/src/Manual Setup/ManualSetup.Table.al
  System Application Modules/.AL-Go/settings.json
  System Application/.AL-Go/settings.json
  Test Framework/.AL-Go/settings.json
Labels: infrastructure

#22568 Distinguish CICD build from PR build
  Build/Scripts/CompileAppInBcContainer.ps1
  Build/Scripts/CreateAppPackageOutput.ps1
  Build/Scripts/EnlistmentHelperFunctions.psm1
Labels: infrastructure

#22616 Remove BuildArtifacts folder in buildoutput
  Build/Scripts/CreateAppPackageOutput.ps1
Labels: infrastructure

#22650 Update baseline version to 21.5.53619.54509
  Build/BuildConfig.json
Labels: automation

#22436 Test copying multiple record links
  Modules/System Tests/Record Link Management/src/RecordLinkMgtTest.Codeunit.al
Labels: processing-PR

#22281 Add reference to Signed XML method
  Modules/System/Cryptography Management/README.md
  Modules/System/Cryptography Management/src/Xml/SignedXml.Codeunit.al
  Modules/System/Cryptography Management/src/Xml/SignedXmlImpl.Codeunit.al
Labels: processing-PR

#22657 Auto merge baseline version PRs
  Build/Scripts/UpdateBaselineVersion.ps1
Labels: infrastructure

#22661 Allow build even when restoring baselines fail
  Build/Scripts/GuardingV2ExtensionsHelper.psm1
Labels: infrastructure

#22487 Enable tests run for System Application
  Build/Scripts/GuardingV2ExtensionsHelper.psm1
  Modules/System Tests/disabledTests.json
  System Application Modules/.AL-Go/ImportTestToolkitToBcContainer.ps1
  System Application/.AL-Go/settings.json
  Test Framework/.AL-Go/settings.json
  Test Stability Tools/.AL-Go/CompileAppInBcContainer.ps1
  Test Stability Tools/.AL-Go/ImportTestToolkitToBcContainer.ps1
  Test Stability Tools/.AL-Go/cloudDevEnv.ps1
  Test Stability Tools/.AL-Go/localDevEnv.ps1
  Test Stability Tools/.AL-Go/settings.json
Labels: infrastructure

#22710 Build translated Test Framework
  Test Framework/.AL-Go/settings.json
Labels: infrastructure

#22717 Update baseline version to 21.5.53619.54729
  Build/BuildConfig.json
Labels: automation
