Repository microsoft/ALAppExtensions, pull requests merged in 2023-04, with the labels that each got.

#23010 Update baseline version to 22.0.54157.55468
  Build/BuildConfig.json
Labels: automation

#22973 Cache baseline packages
  Build/Scripts/EnlistmentHelperFunctions.psm1
  Build/Scripts/GuardingV2ExtensionsHelper.psm1
Labels: infrastructure

#22955 Adding Softera.Bankfeed to Connectivity Apps
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, connectivity-apps

#23130 Update baseline version to 22.0.54157.55786
  Build/BuildConfig.json
Labels: automation

#23143 Add security tools
  .azuredevops/security-tools.gdnsuppress
  .azuredevops/security-tools.yml
  .azuredevops/variables-common.yml
  CODEOWNERS
  System Application Modules/.AL-Go/NewBcContainer.ps1
  System Application/.AL-Go/CompileAppInBcContainer.ps1
  System Application/.AL-Go/NewBcContainer.ps1
  Test Framework/.AL-Go/CompileAppInBcContainer.ps1
  Test Framework/.AL-Go/NewBcContainer.ps1
  Test Stability Tools/.AL-Go/CompileAppInBcContainer.ps1
  build.ps1
Labels: infrastructure
