Repository microsoft/ALAppExtensions, pull requests merged in 2023-08, with the labels that each got.

#24263 Update package versions
  Build/Packages.json
Labels: automation

#24233 Azure Blob Storage - Fix Content Headers
  Modules/System/Azure Blob Services API/src/Helper/ABSHttpContentHelper.Codeunit.al
Labels: ships-in-future-update, processing-PR

#24334 GP July changes to PO migration - Hotfix 2
  Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/History/GPPOPReceiptApply.table.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al
Labels: processing-PR

#23955 Statistical Accounts
  Apps/W1/StatisticalAccounts/app/src/StatAccFinReportingMgt.Codeunit.al
  Apps/W1/StatisticalAccounts/app/src/StatAccReverseEntry.Codeunit.al
Labels: ships-in-future-update, processing-PR

#24253 Add Include function to ABS Optional Parameters
  Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
Labels: processing-PR

#22546 SharePoint: Metadata
  Modules/System/SharePoint/README.md
  Modules/System/SharePoint/src/SharePointClient.Codeunit.al
  Modules/System/SharePoint/src/SharePointClientImpl.Codeunit.al
  Modules/System/SharePoint/src/SharePointEvents.Codeunit.al
  Modules/System/SharePoint/src/helpers/SharePointHttpContent.Codeunit.al
  Modules/System/SharePoint/src/helpers/SharePointRequestHelper.Codeunit.al
  Modules/System/SharePoint/src/helpers/SharePointUriBuilder.Codeunit.al
  Modules/System/SharePoint/src/model/file/SharePointFile.Codeunit.al
  Modules/System/SharePoint/src/model/file/SharePointFile.Table.al
  Modules/System/SharePoint/src/model/listitem/SharePointListItem.Codeunit.al
Labels: processing-PR

#24427 Update package versions
  Build/Packages.json
Labels: internal, automation

#24494 Optimize building modules
  System Application Modules/.AL-Go/settings.json
Labels: internal

#24502 Add Retention Period for 3 Years
  Modules/System Tests/Retention Policy/src/RetentionPeriodTest.Codeunit.al
  Modules/System/Retention Policy/src/Retention Period/RetentionPeriodEnum.Enum.al
  Modules/System/Retention Policy/src/Retention Period/RetentionPeriodImpl.Codeunit.al
Labels: processing-PR

#24517 Improve URI with more Wrappers
  Modules/System Tests/URI/src/UriTest.Codeunit.al
  Modules/System/URI/src/Uri.Codeunit.al
  Modules/System/URI/src/UriKind.Enum.al
Labels: processing-PR

#24426 [Shopify] Shpfy Order Transaction: removed Access Internal
  Apps/W1/Shopify/app/src/Transactions/Tables/ShpfyOrderTransaction.Table.al
Labels: processing-PR

#24477 Add Procedure to Delete E-Mail Accounts
  Modules/System Tests/Email/src/EmailAccountsTest.Codeunit.al
  Modules/System/Email/src/Account/EmailAccount.Codeunit.al
  Modules/System/Email/src/Account/EmailAccountImpl.Codeunit.al
Labels: processing-PR

#24637 GP - Hotfix to correct previous merge issue
  Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al
Labels: processing-PR
