Repository microsoft/ALAppExtensions, pull requests merged in 2023-05, with the labels that each got.

#22811 Fix length of Product Group Code in Shopify Connector
  Apps/W1/Shopify/app/src/Products/Tables/ShpfyShopCollectionMap.Table.al
Labels: processing-PR

#23171 Update baseline version to 22.0.54157.56141
  Build/BuildConfig.json
Labels: automation

#23189 Restores translations for apps during compilation
  .azuredevops/security-tools.yml
  .github/workflows/UpdatePackageVersions.yaml
  Build/BuildConfig.json
  Build/Packages.json
  Build/Scripts/AppTranslations.psm1
  Build/Scripts/CompileAppInBcContainer.ps1
  Build/Scripts/EnlistmentHelperFunctions.psm1
  Build/Scripts/GuardingV2ExtensionsHelper.psm1
  Build/Scripts/UpdateBaselineVersion.ps1
  Build/Scripts/UpdatePackageVersions.ps1
Labels: infrastructure

#22781 Added two BCPT scenarios:
  Other/Tests/BCPT-SampleTests/src/BCPTAdjustCostItemEntries.Codeunit.al
  Other/Tests/BCPT-SampleTests/src/BCPTCalculatePlanWorksheet.Codeunit.al
Labels: processing-PR

#23259 Update package versions
  Build/Packages.json
  Build/Scripts/UpdatePackageVersions.ps1
Labels: automation

#22988 SharePoint library add functions and function overloads
  Modules/System/SharePoint/src/SharePointClient.Codeunit.al
  Modules/System/SharePoint/src/SharePointClientImpl.Codeunit.al
  Modules/System/SharePoint/src/helpers/SharePointRequestHelper.Codeunit.al
Labels: processing-PR

#22771 Nextmarker And ListBlobs overload
  Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSOperationResponse.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSContainerContentHelper.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSHelperLibrary.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
Labels: processing-PR

#22139 Headers.GetValue shielding
  Modules/System/Azure Blob Services API/src/ABSOperationResponse.Codeunit.al
  Modules/System/Azure Storage Services Authorization/src/SharedKey/StorServAuthSharedKey.Codeunit.al
  Modules/System/SharePoint/src/helpers/SharePointOperationResponse.Codeunit.al
Labels: processing-PR

#23267 Wrong field APIReportsFinance- external document no.
  Apps/W1/APIReportsFinance/App/src/APIFinCustLedgEntry.Query.al
  Apps/W1/APIReportsFinance/App/src/APIFinVendLedgEntry.Query.al
  Apps/W1/APIReportsFinance/App/src/APIFinanceGLEntry.Query.al
Labels: processing-PR

#23227 default values for Permissions with Type=TableData
  Modules/System/Permission Sets/src/PermissionImpl.Codeunit.al
Labels: processing-PR

#23540 Update package versions
  Build/Packages.json
Labels: automation
