Repository microsoft/ALAppExtensions, pull requests merged in 2023-01, with the labels that each got.

#21206 Delete record links from a recordset
  Modules/System Tests/Record Link Management/src/RecordLinkMgtTest.Codeunit.al
  Modules/System/Record Link Management/src/RecordLinkImpl.Codeunit.al
  Modules/System/Record Link Management/src/RecordLinkManagement.Codeunit.al
Labels: processing-PR

#21591 SharePoint Auth - Improved README and use the Token Cache
  Modules/System/SharePoint Authorization/README.md
  Modules/System/SharePoint Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al
Labels: processing-PR

#21641 Add workflow to create tags after successful build
  .github/workflows/CICD.yaml
  .github/workflows/CreateBuildTag.yaml
Labels: infrastructure

#21686 Fix create build tag
  .github/workflows/CreateBuildTag.yaml
Labels: infrastructure

#21670 Updated AL-Go System Files
  .github/AL-Go-Settings.json
  .github/RELEASENOTES.copy.md
  .github/workflows/CreateRelease.yaml
Labels: infrastructure

#21638 GP - Fix recent issues with POs
  Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/INTELLIGENTCLOUDHGP.PermissionSetExt.al
  Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al
  Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al
  Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al
  Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOP10100.table.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOP10110.table.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOPPOHeader.table.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOPPOLine.table.al
  Apps/W1/HybridGP/app/src/Migration/Vendors/GPVendorMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/codeunits/GPCloudMigration.codeunit.al
  Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
Labels: processing-PR

#21720 Added new procedure "Permission Set Relation".AddNewPermissionSetRelation
  Modules/System/Permission Sets/src/PermissionSetRelation.Codeunit.al
  Modules/System/Permission Sets/src/PermissionSetRelationImpl.Codeunit.al
Labels: processing-PR

#21782 Do not create build tags on forks
  .github/workflows/CreateBuildTag.yaml
Labels: infrastructure

#21397 Add Direct Banking to Connectivity Apps
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, connectivity-apps

#21721 Corrected ConnectivityApp name to match actual app name.
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, connectivity-apps

#21246 Added time zone management module
  Modules/System Test Libraries/Date & Time/Permissions/Date&TimeExecute.PermissionSet.al
  Modules/System Test Libraries/Date & Time/app.json
  Modules/System Tests/Date & Time/app.json
  Modules/System Tests/Date & Time/src/TimeZoneTest.Codeunit.al
  Modules/System/Date & Time/Permissions/Date&TimeObjects.PermissionSet.al
  Modules/System/Date & Time/app.json
  Modules/System/Date & Time/src/TimeZone.Codeunit.al
  Modules/System/Date & Time/src/TimeZoneImpl.Codeunit.al
  Modules/System/Date & Time/src/TimeZoneInfoInitializer.Codeunit.al
  Modules/System/Permissions/SystemApplicationObjects.PermissionSet.al
Labels: ships-in-future-update, processing-PR

#21831 Add unusedALGoSystemFiles setting
  .github/AL-Go-Settings.json
  .github/RELEASENOTES.copy.md
  .github/workflows/AddExistingAppOrTestApp.yaml
  .github/workflows/CICD.yaml
  .github/workflows/CreateApp.yaml
  .github/workflows/CreateOnlineDevelopmentEnvironment.yaml
  .github/workflows/CreatePerformanceTestApp.yaml
  .github/workflows/CreateRelease.yaml
  .github/workflows/CreateTestApp.yaml
  .github/workflows/Current.yaml
  .github/workflows/IncrementVersionNumber.yaml
  .github/workflows/NextMajor.yaml
  .github/workflows/NextMinor.yaml
  .github/workflows/PublishToEnvironment.yaml
  .github/workflows/UpdateGitHubGoSystemFiles.yaml
  Modules/.AL-Go/cloudDevEnv.ps1
  Modules/.AL-Go/localDevEnv.ps1
Labels: infrastructure

#21843 [Guided Experience] Add Translation For Setup Object Short Title
  Modules/System/Guided Experience/src/Guided Experience/GuidedExperience.Codeunit.al
Labels: processing-PR
