Repository microsoft/ALAppExtensions, pull requests merged in 2023-07, with the labels that each got.

#23970 Update package versions
  Build/Packages.json
Labels: automation

#23213 permissions caption and name
  Modules/System/Permission Sets/src/ExpandedPermissions.Page.al
  Modules/System/Permission Sets/src/PermissionImpl.Codeunit.al
  Modules/System/Permission Sets/src/TenantPermissionSubForm.page.al
Labels: processing-PR

#24016 [Shopify] Remove access internal from Payment tables
  Apps/W1/Shopify/README.md
  Apps/W1/Shopify/app/src/Payments/Tables/ShpfyPaymentTransaction.Table.al
  Apps/W1/Shopify/app/src/Payments/Tables/ShpfyPayout.Table.al
Labels: ships-in-future-update, processing-PR

#23781 Extend Azure Blob Services API with Content Type
  Modules/System/Azure Blob Services API/README.md
  Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al
  Modules/System/Azure Blob Services API/src/ABSContainerClient.Codeunit.al
  Modules/System/Azure Blob Services API/src/Helper/ABSHttpContentHelper.Codeunit.al
Labels: processing-PR

#24050 Update package versions
  Build/Packages.json
Labels: automation

#24139 Update package versions
  Build/Packages.json
Labels: automation

#23472 actions for processing multiple permissions
  Modules/System Tests/Permission Sets/src/UpdatingPermissionTests.Codeunit.al
  Modules/System/Permission Sets/src/PermissionImpl.Codeunit.al
  Modules/System/Permission Sets/src/TenantPermissionSubForm.page.al
Labels: processing-PR

#24202 Update package versions
  Build/Packages.json
Labels: automation

#24171 Enhance UI of extension settings
  Modules/System/Extension Management/src/ExtensionSettings.Page.al
Labels: processing-PR
