Repository microsoft/ALAppExtensions, pull requests merged in 2024-11, with the labels that each got.

#27541 [Shopify] - Add Item As Variant Tests
  Apps/W1/Shopify/test/Products/ShpfyCreateItemAsVariantSub.Codeunit.al
  Apps/W1/Shopify/test/Products/ShpfyCreateItemVariantTest.Codeunit.al
Labels: processing-PR, linked, Integration

#27555 [Shopify] Fix sync catalog price issue
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLNextCatalogPrices.Codeunit.al
Labels: linked, Integration

#27578 [Shopify] Shopify Return Location on Refunds tests
  Apps/W1/Shopify/app/src/Order Refunds/Codeunits/ShpfyRefundsAPI.Codeunit.al
  Apps/W1/Shopify/test/Order Refunds/ShpfyOrderRefundTest.Codeunit.al
  Apps/W1/Shopify/test/Order Refunds/ShpfyOrderRefundsHelper.Codeunit.al
Labels: processing-PR, linked, Integration

#27570 [Shopify] - Export Posted Sales Invoices to Shopify as Orders Tests
  Apps/W1/Shopify/test/Invoices/ShpfyInvoicesAPISubscriber.Codeunit.al
  Apps/W1/Shopify/test/Invoices/ShpfyInvoicesTest.Codeunit.al
  Apps/W1/Shopify/test/app.json
Labels: ships-in-future-update, processing-PR, linked, Integration

#27587 Reenable test execution
  Build/BuildConfig.json
  Build/Scripts/ImportTestDataInBcContainer.ps1
  Build/Scripts/RunTestsInBcContainer.ps1
  Build/projects/1st Party Apps Tests (W1)/.AL-Go/ImportTestDataInBcContainer.ps1
  Build/projects/1st Party Apps Tests (W1)/.AL-Go/settings.json
Labels: internal
