Repository microsoft/ALAppExtensions, pull requests merged in 2024-01, with the labels that each got.

#25644 Bcpt scenarios
  Other/Tests/BCPT-SampleTests/src/BCPTCreateCustomer.Codeunit.al
  Other/Tests/BCPT-SampleTests/src/BCPTCreateItem.Codeunit.al
  Other/Tests/BCPT-SampleTests/src/BCPTCreateVendor.Codeunit.al
  Other/Tests/BCPT-SampleTests/src/TestCodeunitsWithParams.Enum.al
Labels: processing-PR, linked

#25659 [main] Update BC Artifact version
  .github/AL-Go-Settings.json
Labels: automation

#25716 [main] Update BC Artifact version
  .github/AL-Go-Settings.json
Labels: automation

#25613 GP - December 2023 enhancements
  Apps/W1/HybridGP/app/Permissions/INTELLIGENTCLOUDHGP.PermissionSetExt.al
  Apps/W1/HybridGP/app/src/Migration/GPTables/GPSY01200.Table.al
  Apps/W1/HybridGP/app/src/Migration/Items/GPItemMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/CheckBooks/GPCheckbookMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/WizardIntegration.codeunit.al
  Apps/W1/HybridGP/app/src/codeunits/HybridGPWizard.codeunit.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyAddSettingsList.Page.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyMigrationSettings.Page.al
  Apps/W1/HybridGP/app/src/pages/GPMigrationConfiguration.Page.al
  Apps/W1/HybridGP/app/src/pages/IntelligentCloudExtension.PageExt.al
  Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al
  Apps/W1/HybridGP/test/src/GPCheckBookTests.codeunit.al
  Apps/W1/HybridGP/test/src/GPItemTransactionTests.codeunit.al
Labels: ships-in-future-update, processing-PR

#25721 Service Declaration Bugfix for Standard Sales Lines + Standard Purchase Lines
  Apps/W1/ServiceDeclaration/app/src/Processing/ServiceDeclarationMgt.Codeunit.al
Labels: processing-PR
