Repository microsoft/ALAppExtensions, pull requests merged in 2024-08, with the labels that each got.

#26712 [Shopify] Add items as product variants
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLGetProductOptions.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLProductVariantDelete.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Enums/ShpfyGraphQLType.Enum.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyCreateItemAsVariant.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyCreateProduct.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyVariantAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Pages/ShpfyVariants.Page.al
  Apps/W1/Shopify/app/src/Products/Reports/ShpfyAddItemAsVariant.Report.al
Labels: processing-PR, linked, Integration

#26886 Update Yavrio in ConnectivityAppDefinitions.Codeunit.al
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: linked, Integration

#26730 [Fix] URL maximum length in E-Document Integration
  Apps/W1/EDocument/app/src/Log/EDocumentIntegrationLog.Table.al
  Apps/W1/EDocument/app/src/Log/EDocumentIntegrationLogs.Page.al
  Apps/W1/EDocument/app/src/Log/EDocumentLog.Codeunit.al
  Apps/W1/EDocument/test/src/Log/EDocLogTest.Codeunit.al
Labels: processing-PR, linked, Integration

#26883 Update InstallSECore.codeunit.al
  Apps/SE/SECore/app/src/Codeunits/InstallSECore.codeunit.al
Labels: processing-PR, linked, Integration

#26821 GP Updates - July 2024
  Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistGenJournalLines.Page.al
  Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistInventoryTrx.Page.al
  Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistPayablesDocument.Page.al
  Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistPurchaseRecv.Page.al
  Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistReceivablesDocument.Page.al
  Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistSalesTrx.Page.al
  Apps/W1/DynamicsGPHistoricalData/app/src/Tables/HistGenJournalLine.Table.al
  Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/INTELLIGENTCLOUDHGP.PermissionSetExt.al
  Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al
  Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al
  Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al
  Apps/W1/HybridGP/app/src/Migration/Customers/GPCustomerMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/GPTables/GPIV00104.Table.al
  Apps/W1/HybridGP/app/src/Migration/GPTables/GPPopulateCombinedTables.Codeunit.al
  Apps/W1/HybridGP/app/src/Migration/History/GPPM10200.Table.al
  Apps/W1/HybridGP/app/src/Migration/History/GPPM30300.Table.al
  Apps/W1/HybridGP/app/src/Migration/Items/GPItem.table.al
  Apps/W1/HybridGP/app/src/Migration/Items/GPItemMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Vendors/GPVendorMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/codeunits/GPCloudMigration.codeunit.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyAddSettingsList.Page.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyMigrationSettings.Page.al
  Apps/W1/HybridGP/app/src/pages/GPMigrationConfiguration.Page.al
  Apps/W1/HybridGP/app/src/pages/GPUpgradeSettings.Page.al
  Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al
  Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
  Apps/W1/HybridGP/test/src/GPItemTests.codeunit.al
  Apps/W1/HybridGP/test/src/GPSettingsTests.codeunit.al
Labels: processing-PR, linked, Finance

#26981 [Shopify][BC Idea]: Enhancing Shopify Connector for Accurate Price Synchronization with Business Central based on Customer
  Apps/W1/Shopify/app/src/Catalogs/Pages/ShpfyCatalogs.Page.al
  Apps/W1/Shopify/app/src/Catalogs/Tables/ShpfyCatalog.Table.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductPriceCalc.Codeunit.al
  Apps/W1/Shopify/test/Catalogs/ShpfyCatalogPricesTest.Codeunit.al
  Apps/W1/Shopify/test/Products/ShpfyProductInitTest.Codeunit.al
Labels: processing-PR, linked, Integration

#26216 [Shopify] Add Translations Export to Products and Variants
  Apps/W1/Shopify/app/src/Base/Pages/ShpfyShopCard.Page.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLOrderTransactions.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLShopLocales.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLTranslResource.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLTranslationsRegister.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Enums/ShpfyGraphQLType.Enum.al
  Apps/W1/Shopify/app/src/Integration/Codeunits/ShpfyAuthenticationMgt.Codeunit.al
  Apps/W1/Shopify/app/src/PermissionSets/ShpfyEdit.PermissionSet.al
  Apps/W1/Shopify/app/src/PermissionSets/ShpfyRead.PermissionSet.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductEvents.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductExport.Codeunit.al
  Apps/W1/Shopify/app/src/Translations/Codeunits/ICreateTranslation/ShpfyCreateTranslProduct.Codeunit.al
  Apps/W1/Shopify/app/src/Translations/Codeunits/ICreateTranslation/ShpfyCreateTranslVariant.Codeunit.al
  Apps/W1/Shopify/app/src/Translations/Codeunits/ShpfyTranslationApi.Codeunit.al
  Apps/W1/Shopify/app/src/Translations/Codeunits/ShpfyTranslationMgt.Codeunit.al
  Apps/W1/Shopify/app/src/Translations/Enums/ShpfyResourceType.Enum.al
  Apps/W1/Shopify/app/src/Translations/Interfaces/ShpfyICreateTranslation.Interface.al
  Apps/W1/Shopify/app/src/Translations/Pages/ShpfyLanguages.Page.al
  Apps/W1/Shopify/app/src/Translations/Tables/ShpfyLanguage.Table.al
  Apps/W1/Shopify/app/src/Translations/Tables/ShpfyTranslation.Table.al
Labels: processing-PR, linked, Integration

#26185 [Shopify] Add Metafields to Products and Variants
  Apps/W1/Shopify/app/app.json
  Apps/W1/Shopify/app/src/Base/Tables/ShpfyMetafield.Table.al
  Apps/W1/Shopify/app/src/Customers/Codeunits/ShpfyCustomerExport.Codeunit.al
  Apps/W1/Shopify/app/src/Customers/Tables/ShpfyCustomer.Table.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLMetafieldsSet.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLProductById.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLProductMetafieldIds.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLVariantById.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLVariantMetafieldIds.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Enums/ShpfyGraphQLType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeBoolean.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeCollectRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeColor.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeDate.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeDateTime.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeDimension.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeFileRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeInteger.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeJson.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeMetaobjRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeMixedRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeMoney.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeMultiText.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeNumDecimal.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeNumInteger.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypePageRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeProductRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeSingleText.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeString.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeUrl.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeVariantRef.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeVolume.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IMetafieldType/ShpfyMtfldTypeWeight.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IOwnerType/ShpfyMetafieldOwnerCustomer.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IOwnerType/ShpfyMetafieldOwnerProduct.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/IOwnerType/ShpfyMetafieldOwnerVariant.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Codeunits/ShpfyMetafieldAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Metafields/Enums/ShpfyMetafieldDimensionType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Enums/ShpfyMetafieldOwnerType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Enums/ShpfyMetafieldType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Enums/ShpfyMetafieldValueType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Enums/ShpfyMetafieldVolumeType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Enums/ShpfyMetafieldWeightType.Enum.al
  Apps/W1/Shopify/app/src/Metafields/Interfaces/ShpfyIMetafieldOwnerType.Interface.al
  Apps/W1/Shopify/app/src/Metafields/Interfaces/ShpfyIMetafieldType.Interface.al
  Apps/W1/Shopify/app/src/Metafields/Pages/ShpfyMetafieldAssistEdit.Page.al
  Apps/W1/Shopify/app/src/Metafields/Pages/ShpfyMetafields.Page.al
  Apps/W1/Shopify/app/src/Metafields/Tables/ShpfyMetafield.Table.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductExport.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyVariantAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Products/Pages/ShpfyProducts.Page.al
  Apps/W1/Shopify/app/src/Products/Pages/ShpfyVariants.Page.al
  Apps/W1/Shopify/app/src/Products/Tables/ShpfyProduct.Table.al
  Apps/W1/Shopify/app/src/Products/Tables/ShpfyVariant.Table.al
Labels: processing-PR, linked, Integration

#26748 [Shopify] Connector - Export Posted Sales Invoices to Shopify as Orders
  Apps/W1/Shopify/app/app.json
  Apps/W1/Shopify/app/src/Base/Pages/ShpfyShopCard.Page.al
  Apps/W1/Shopify/app/src/Base/Tables/ShpfyShop.Table.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLDraftOrderComplete.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLFulfillOrder.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLGetFulfillments.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLPaymentTerms.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLShopLocales.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Codeunits/ShpfyGQLTranslationsRegister.Codeunit.al
  Apps/W1/Shopify/app/src/GraphQL/Enums/ShpfyGraphQLType.Enum.al
  Apps/W1/Shopify/app/src/Integration/Codeunits/ShpfyAuthenticationMgt.Codeunit.al
  Apps/W1/Shopify/app/src/Invoicing/Codeunits/ShpfyDraftOrdersAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Invoicing/Codeunits/ShpfyFulfillmentAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Invoicing/Codeunits/ShpfyPostedInvoiceExport.Codeunit.al
  Apps/W1/Shopify/app/src/Invoicing/Codeunits/ShpfyUpdateSalesInvoice.Codeunit.al
  Apps/W1/Shopify/app/src/Invoicing/PageExt/ShpfySalesInvoiceUpdate.PageExt.al
  Apps/W1/Shopify/app/src/Invoicing/Reports/ShpfySyncInvoicesToShpfy.Report.al
  Apps/W1/Shopify/app/src/Invoicing/Tables/ShpfyInvoiceHeader.Table.al
  Apps/W1/Shopify/app/src/Order handling/Codeunits/ShpfyImportOrder.Codeunit.al
  Apps/W1/Shopify/app/src/Order handling/Codeunits/ShpfyProcessOrder.Codeunit.al
  Apps/W1/Shopify/app/src/Order handling/Tables/ShpfyOrderHeader.Table.al
  Apps/W1/Shopify/app/src/Payments/Codeunits/ShpfyPaymentTermsAPI.Codeunit.al
  Apps/W1/Shopify/app/src/Payments/Pages/ShpfyPaymentTermsMapping.Page.al
  Apps/W1/Shopify/app/src/Payments/Tables/ShpfyPaymentTerms.Table.al
  Apps/W1/Shopify/app/src/PermissionSets/ShpfyEdit.PermissionSet.al
  Apps/W1/Shopify/app/src/PermissionSets/ShpfyRead.PermissionSet.al
Labels: processing-PR, linked, Integration

#27100 GP - Update migrations with 1099 data to use the new IRS Forms app.
  Apps/US/HybridGP_US/app/Permissions/HybridGPUSObjects.PermissionSet.al
  Apps/US/HybridGP_US/app/app.json
  Apps/US/HybridGP_US/app/src/Codeunits/GPCloudMigrationUS.Codeunit.al
  Apps/US/HybridGP_US/app/src/Codeunits/GPIRSFormData.Codeunit.al
  Apps/US/HybridGP_US/app/src/Codeunits/GPPopulateVendor1099Data.Codeunit.al
  Apps/US/HybridGP_US/test/app.json
  Apps/US/HybridGP_US/test/src/MigrationVendor1099Tests.Codeunit.al
Labels: processing-PR, linked
