Repository microsoft/ALAppExtensions, pull requests merged in 2024-02, with the labels that each got.

#25777 GP migration - Hotfix for email and item transaction issues
  Apps/US/HybridGP_US/app/src/TableExt/GPCompanyAddSettingsExt.TableExt.al
  Apps/US/HybridGP_US/test/src/MigrationVendor1099Tests.Codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Customers/GPCustomerMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/GPTables/GPSY01200.Table.al
  Apps/W1/HybridGP/app/src/Migration/Items/GPItemMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Vendors/GPVendorMigrator.codeunit.al
Labels: processing-PR

#25403 Update ConnectivityAppDefinitions.Codeunit.al
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, connectivity-apps, linked

#25831 GP - Enhancements to Payment Terms creation, visibility of unposted batches, and Migration Log
  Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al
  Apps/W1/HybridGP/app/Permissions/INTELLIGENTCLOUDHGP.PermissionSetExt.al
  Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al
  Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al
  Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al
  Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/GPPaymentTerms.Page.al
  Apps/W1/HybridGP/app/src/Migration/Support/GPPaymentTerms.table.al
  Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/codeunits/HybridGPWizard.codeunit.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyAddSettingsList.Page.al
  Apps/W1/HybridGP/app/src/pages/GPMigrationWarnings.Page.al
  Apps/W1/HybridGP/app/src/pages/HybridGPErrorsOverviewFb.page.al
  Apps/W1/HybridGP/app/src/pages/HybridGPOverviewFb.Page.al
  Apps/W1/HybridGP/app/src/pages/IntelligentCloudExtension.PageExt.al
  Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al
  Apps/W1/HybridGP/app/src/tables/GPMigrationWarnings.Table.al
  Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
Labels: processing-PR, linked

#25990 [Bug]: Is not posible to create a G/L Account Mapping using Client
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccount.Table.al
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccountCategory.Table.al
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccounts.Page.al
Labels: linked
