Repository microsoft/ALAppExtensions, pull requests merged in 2024-05, with the labels that each got.

#26403 GP Updates - April 2024
  Apps/W1/HybridGP/app/src/Migration/Items/GPItemMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/CheckBooks/GPCheckbookMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al
  Apps/W1/HybridGP/app/src/Migration/Vendors/GPVendorMigrator.codeunit.al
  Apps/W1/HybridGP/app/src/codeunits/FiscalPeriods.codeunit.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyAddSettingsList.Page.al
  Apps/W1/HybridGP/app/src/pages/GPCompanyMigrationSettings.Page.al
  Apps/W1/HybridGP/app/src/pages/GPMigrationConfiguration.Page.al
  Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al
  Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
  Apps/W1/HybridGP/test/src/GPSettingsTests.codeunit.al
Labels: processing-PR, linked, Integration

#26133 Prevent duplicate record in the Master Data Management - Synchronization Tables list
  Apps/W1/MasterDataManagement/app/app.json
  Apps/W1/MasterDataManagement/app/src/pages/MasterDataSynchTables.Page.al
  Apps/W1/MasterDataManagement/test library/src/LibraryMasterDataMgt.Codeunit.al
  Apps/W1/MasterDataManagement/test library/src/MDMTestTableA.Table.al
  Apps/W1/MasterDataManagement/test library/src/MDMTestTableB.Table.al
  Apps/W1/MasterDataManagement/test/src/MasterDataMgtSetupTests.Codeunit.al
Labels: processing-PR, linked, Integration

#26438 Sustainability Journal Line - Extensibility for Default Dimensions
  Apps/W1/Sustainability/app/src/Journal/SustainabilityJnlLine.Table.al
Labels: processing-PR, linked, Finance

#26564 Update ConnectivityAppDefinitions.Codeunit.al
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: linked
