Repository microsoft/ALAppExtensions, pull requests merged in 2024-10, with the labels that each got.

#27463 Service Declaration - Service Line Use Correct Header
  Apps/W1/ServiceDeclaration/app/src/ServiceDocuments/ServDeclServLine.TableExt.al
Labels: processing-PR, linked, SCM

#27464 Service Declaration Bugfix for Temp Sales / Purchase Lines
  Apps/W1/ServiceDeclaration/app/src/PurchaseDocuments/ServDeclPurchLine.TableExt.al
  Apps/W1/ServiceDeclaration/app/src/SalesDocuments/ServDeclSalesLine.TableExt.al
Labels: processing-PR, linked, SCM

#27350 [Intrastat Core] Changes to "Validate Codeunit ID" and "Content Codeunit ID" behavior on "Intrastat Report" page
  Apps/W1/Intrastat/app/src/IntrastatReport.Page.al
Labels: processing-PR, linked, Integration

#27521 #943 Intrastat default transactions types
  Apps/W1/Intrastat/app/src/IntrastatRepCustTemCard.PageExt.al
  Apps/W1/Intrastat/app/src/IntrastatReportCustTempl.TableExt.al
Labels: processing-PR, linked, Finance

#27539 [Shopify] Log Skipped Records on export processes
  Apps/W1/Shopify/app/src/Base/Codeunits/ShpfyInstaller.Codeunit.al
  Apps/W1/Shopify/app/src/Companies/Codeunits/ShpfyCompanyExport.Codeunit.al
  Apps/W1/Shopify/app/src/Customers/Codeunits/ShpfyCustomerExport.Codeunit.al
  Apps/W1/Shopify/app/src/Invoicing/Codeunits/ShpfyPostedInvoiceExport.Codeunit.al
  Apps/W1/Shopify/app/src/Logs/Codeunits/ShpfySkipRecordMgt.Codeunit.al
  Apps/W1/Shopify/app/src/Logs/Codeunits/ShpfySkippedRecord.Codeunit.al
  Apps/W1/Shopify/app/src/Logs/Pages/ShpfySkippedRecords.Page.al
  Apps/W1/Shopify/app/src/Logs/Tables/ShpfySkippedRecord.Table.al
  Apps/W1/Shopify/app/src/PermissionSets/ShpfyEdit.PermissionSet.al
  Apps/W1/Shopify/app/src/PermissionSets/ShpfyRead.PermissionSet.al
  Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductExport.Codeunit.al
  Apps/W1/Shopify/app/src/Shipping/Codeunits/ShpfyExportShipments.Codeunit.al
  Apps/W1/Shopify/app/src/Shipping/Reports/ShpfySyncShipmToShopify.Report.al
  Apps/W1/Shopify/test/Logs/ShpfySkippedRecordLogSub.Codeunit.al
  Apps/W1/Shopify/test/Logs/ShpfySkippedRecordLogTest.Codeunit.al
  Apps/W1/Shopify/test/Shipping/ShpfyShippingHelper.Codeunit.al
  Apps/W1/Shopify/test/Shipping/ShpfyShippingTest.Codeunit.al
Labels: processing-PR, linked, Integration
