Repository microsoft/ALAppExtensions, pull requests merged in 2025-04, with the labels that each got.

#28132 New Event OnQRBillImportDecodeBeforeQRBillImport for Override the QRScan Process
  Apps/CH/SwissQRBill/app/src/IncomingDocuments/SwissQRBillIncomingDoc.Codeunit.al
  Apps/CH/SwissQRBill/app/src/purchases/SwissQRBillPurchases.Codeunit.al
Labels: processing-PR, linked, Finance

#28454 Update the extensibility-request issue template
  .github/ISSUE_TEMPLATE/extensibility-request.yaml
Labels: internal

#28303 [Bugfix] "Swiss QR-Bill Incoming Doc" UpdatePurchDocFromIncDoc Fill "Bank Code"
  Apps/CH/SwissQRBill/app/src/IncomingDocuments/SwissQRBillIncomingDoc.Codeunit.al
  Apps/CH/SwissQRBill/app/src/purchases/SwissQRBillPurchases.Codeunit.al
  Apps/CH/SwissQRBill/test/src/SwissQRBillTestLibrary.Codeunit.al
  Apps/CH/SwissQRBill/test/src/SwissQRBillTestPurchases.Codeunit.al
Labels: processing-PR, Finance

#28465 Fix URLs for images and links in readme for Contoso demo tool
  Apps/W1/ContosoCoffeeDemoDataset/app/README.md
Labels: processing-PR, linked, Integration

#28473 Update issue form
  .github/ISSUE_TEMPLATE/extensibility-request.yaml
Labels: internal

#28452 Make dates language agnostic in Excel Reports
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/Customer/CustomerTopListExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/FixedAsset/FixedAssetAnalysisExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/FixedAsset/FixedAssetDetailsExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/FixedAsset/FixedAssetProjectedValueExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/ConsolidatedTrialBalanceExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalanceBudgetExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalanceExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalancePrevYearExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalancebyPeriodExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/Purchase/AgedAccountsPayableExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/Sales/AgedAccountsReceivableExcel.xlsx
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/Vendor/VendorTopListExcel.xlsx
  Apps/W1/ExcelReports/app/src/Customer/EXRCustomerTopList.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRAgedAccPayableExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRAgedAccountsRecExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRConsolidatedTrialBalance.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetAnalysisExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetDetailsExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetProjected.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalPrevYearExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalanceBudgetExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalanceExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalbyPeriodExcel.Report.al
  Apps/W1/ExcelReports/app/src/Vendor/EXRVendorTopList.Report.al
  Apps/W1/Sustainability/app/src/Reports/EmissionByCategory.Report.al
  Apps/W1/Sustainability/app/src/Reports/EmissionByCategory.xlsx
  Apps/W1/Sustainability/app/src/Reports/EmissionPerFacility.Report.al
  Apps/W1/Sustainability/app/src/Reports/EmissionPerFacility.xlsx
  Apps/W1/Sustainability/app/src/Reports/TotalEmissions.Report.al
  Apps/W1/Sustainability/app/src/Reports/TotalEmissions.xlsx
Labels: processing-PR, linked, Finance

#28504 [SAFT] Add missing captions
  Apps/W1/AuditFileExport/app/src/AuditFileExportFormat.Enum.al
  Apps/W1/AuditFileExport/app/src/CheckAuditData/AuditDataCheckStatus.Enum.al
  Apps/W1/AuditFileExport/app/src/ExportEngine/AuditFileExportDataClass.Enum.al
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/CopyGLAccountMapping.Report.al
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/GLAccMappingPeriodType.Enum.al
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccountType.Enum.al
  Apps/W1/AuditFileExport/app/src/Permissions/AuditExportEdit.PermissionSet.al
  Apps/W1/AuditFileExport/app/src/Permissions/AuditExportRead.PermissionSet.al
  Apps/W1/AuditFileExport/app/src/Setup/AuditFileExportSetup.Page.al
  Apps/W1/SAF-T/app/src/CheckAuditDataSAFT/MissingFieldSAFT.Table.al
  Apps/W1/SAF-T/app/src/ExportEngineSAFT/AuditFileExportHeaderSAFT.TableExt.al
  Apps/W1/SAF-T/app/src/MasterDataMapping/DimensionSAFT.TableExt.al
  Apps/W1/SAF-T/app/src/MasterDataMapping/SourceCodeSAFT.Table.al
  Apps/W1/SAF-T/app/src/MasterDataMapping/VATPostingSetupSAFT.TableExt.al
  Apps/W1/SAF-T/app/src/Permissions/SAFTEdit.PermissionSet.al
  Apps/W1/SAF-T/app/src/Permissions/SAFTRead.PermissionSet.al
  Apps/W1/SAF-T/app/src/SAFTModification.Enum.al
  Apps/W1/SAF-T/app/src/Setup/AuditExportDataTypeSAFT.EnumExt.al
  Apps/W1/SAF-T/app/src/Setup/AuditFileExportSetupSAFT.TableExt.al
  Apps/W1/SAF-T/app/src/Setup/CompanyContactSAFT.TableExt.al
  Apps/W1/SAF-T/app/src/Setup/SAFTWizard.Page.al
Labels: processing-PR, linked, Finance

#28450 Audit File Export. Remove the loop by export documents when restart task
  Apps/W1/AuditFileExport/app/src/ExportEngine/AuditFileExportMgt.Codeunit.al
Labels: processing-PR, linked, Finance
