Repository microsoft/ALAppExtensions, pull requests merged in 2025-03, with the labels that each got.

#28108 Fixed Asset Details adjustments from feedback
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/FixedAsset/FixedAssetDetailsExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetDetailsExcel.Report.al
Labels: processing-PR, linked, Finance

#28121 Modernize Excel Layout - Trial Balance Previous Year
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalancePrevYearExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalPrevYearExcel.Report.al
Labels: processing-PR, linked, Finance

#28105 Vendor Top List adjustment from feedback
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/Vendor/VendorTopListExcel.xlsx
  Apps/W1/ExcelReports/app/src/Vendor/EXRVendorTopList.Report.al
Labels: processing-PR, linked, Finance

#28134 Modernize Excel Layout - Trial Balance
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalanceExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalanceExcel.Report.al
Labels: processing-PR, linked, Finance

#28137 Modernize Excel Layout - Emission By Category
  Apps/W1/Sustainability/app/src/Reports/EmissionByCategory.Report.al
  Apps/W1/Sustainability/app/src/Reports/EmissionByCategory.xlsx
Labels: processing-PR, linked, Finance

#28143 Modernize Excel Layout - Fixed Asset Projected
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/FixedAsset/FixedAssetProjectedValueExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetProjected.Report.al
Labels: processing-PR, linked, Finance

#28146 Modernize Excel Layout - Consolidated Trial Balance
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/ConsolidatedTrialBalanceExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRConsolidatedTrialBalance.Report.al
Labels: processing-PR, linked, Finance

#28139 Modernize Excel Layout - Emission Per Facility
  Apps/W1/Sustainability/app/src/Reports/EmissionPerFacility.Report.al
  Apps/W1/Sustainability/app/src/Reports/EmissionPerFacility.xlsx
Labels: processing-PR, linked, Finance

#28150 Modernize Excel Layout - Aged Accounts Payables
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/Purchase/AgedAccountsPayableExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRAgedAccPayableExcel.Report.al
Labels: processing-PR, linked, Finance

#28158 Modernize Excel Layout - Total Emissions
  Apps/W1/Sustainability/app/src/Reports/TotalEmissions.Report.al
  Apps/W1/Sustainability/app/src/Reports/TotalEmissions.xlsx
Labels: processing-PR, linked, Finance

#28144 Modernize Excel Layout - Trial Balance Budget
  Apps/W1/ExcelReports/app/ReportLayouts/Excel/GeneralLedger/TrialBalanceBudgetExcel.xlsx
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalanceBudgetExcel.Report.al
Labels: processing-PR, linked, Finance

#28181 Update ConnectivityAppDefinitions.Codeunit.al
  Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Labels: processing-PR, linked, Integration

#28073 Plumbline - Hybrid SL update20250206
  Apps/W1/HybridSL/app/app.json
  Apps/W1/HybridSL/app/src/Migration/Accounts/SLAccountMigrator.Codeunit.al
  Apps/W1/HybridSL/app/src/Migration/Customers/SLCustomerMigrator.Codeunit.al
  Apps/W1/HybridSL/app/src/Migration/SLTables/SLPopulateAccountHistory.Codeunit.al
Labels: processing-PR, Integration

#28171 Add The Type field on page "Standard Accounts"
  Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccounts.Page.al
Labels: ships-in-future-update, processing-PR, linked, Finance

#28331 Insert ApplicationArea to Outlook API Setup page
  Apps/W1/Email - Outlook REST API/app/src/EmailOutlookAPISetup.Page.al
Labels: linked, Integration

#28317 Update Excel report caption and about text
  Apps/W1/ExcelReports/app/src/Customer/EXRCustomerTopList.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRAgedAccPayableExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRAgedAccountsRecExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRConsolidatedTrialBalance.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetAnalysisExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetDetailsExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRFixedAssetProjected.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalPrevYearExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalanceBudgetExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalanceExcel.Report.al
  Apps/W1/ExcelReports/app/src/Financials/EXRTrialBalbyPeriodExcel.Report.al
  Apps/W1/ExcelReports/app/src/RoleCenters/EXRARRoleCenter.PageExt.al
  Apps/W1/ExcelReports/app/src/RoleCenters/EXRAccountantRoleCenter.PageExt.al
  Apps/W1/ExcelReports/app/src/RoleCenters/EXRFinRoleCenter.PageExt.al
  Apps/W1/ExcelReports/app/src/RoleCenters/ExtBusManagerRoleCenter.PageExt.al
  Apps/W1/ExcelReports/app/src/RoleCenters/ExtCompanyDetail.PageExt.al
  Apps/W1/ExcelReports/app/src/Vendor/EXRVendorTopList.Report.al
Labels: processing-PR, linked, Finance

#28398 Add Fields to Vendor Templ. for Intrastat
  Apps/W1/Intrastat/app/src/BaseAppExtensions/Purchase/IntrastatRepVendTemCard.PageExt.al
  Apps/W1/Intrastat/app/src/BaseAppExtensions/Purchase/IntrastatReportVendorTempl.TableExt.al
Labels: processing-PR, linked, SCM

#28350 Fix CopyFile in Ext. File Share Connector Impl
  Apps/W1/External File Storage - Azure File Service Connector/app/src/ExtFileShareConnectorImpl.Codeunit.al
Labels: processing-PR, linked, Integration

#28301 [BugFix] "Swiss QR-Bill Incoming Doc" UpdatePurchDocFromIncDoc Don't Override Purchase Field
  Apps/CH/SwissQRBill/app/src/IncomingDocuments/SwissQRBillIncomingDoc.Codeunit.al
  Apps/CH/SwissQRBill/test/src/SwissQRBillTestPurchases.Codeunit.al
Labels: processing-PR, linked, Finance
